name: Test code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testCode:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x86
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Test with tox
      run: tox
    - name: Lint with flake8
      run: runlint
      shell: cmd
    - name: Get sha256
      run: runsha _tests\testData\fake.nvda-addon
      shell: cmd
      