name: Test validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testValidate:

    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x86
    - name: Test validate
      run: runValidate.bat clipContentsDesigner\13.0.json
      shell: cmd
      